#!/bin/bash
BOOTSTRAP_IMAGE=bootstrap-developer-shell
DOCKER_VERSION=`docker version -f '{{.Server.Version}}'`

docker build -f Dockerfile.developer-shell -t ${BOOTSTRAP_IMAGE} . 
docker run --rm  -v /usr/bin/docker:/usr/bin/docker -v /var/run/docker.sock:/var/run/docker.sock -v `pwd`:/nds/src ${BOOTSTRAP_IMAGE} make
